pipeline {
    agent any

    stages {
        stage('run docker') {
            steps {
                sh "cd Task1"
                sh 'docker rm -f $(docker ps -aq) || true'
                sh "docker-compose up -d "
            }
        }
    }
}
